<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>Test Report</title>
    <link href="assets/style.css" rel="stylesheet" type="text/css"/></head>
  <body onLoad="init()">
    <script>/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */


function toArray(iter) {
    if (iter === null) {
        return null;
    }
    return Array.prototype.slice.call(iter);
}

function find(selector, elem) { // eslint-disable-line no-redeclare
    if (!elem) {
        elem = document;
    }
    return elem.querySelector(selector);
}

function findAll(selector, elem) {
    if (!elem) {
        elem = document;
    }
    return toArray(elem.querySelectorAll(selector));
}

function sortColumn(elem) {
    toggleSortStates(elem);
    const colIndex = toArray(elem.parentNode.childNodes).indexOf(elem);
    let key;
    if (elem.classList.contains('result')) {
        key = keyResult;
    } else if (elem.classList.contains('links')) {
        key = keyLink;
    } else {
        key = keyAlpha;
    }
    sortTable(elem, key(colIndex));
}

function showAllExtras() { // eslint-disable-line no-unused-vars
    findAll('.col-result').forEach(showExtras);
}

function hideAllExtras() { // eslint-disable-line no-unused-vars
    findAll('.col-result').forEach(hideExtras);
}

function showExtras(colresultElem) {
    const extras = colresultElem.parentNode.nextElementSibling;
    const expandcollapse = colresultElem.firstElementChild;
    extras.classList.remove('collapsed');
    expandcollapse.classList.remove('expander');
    expandcollapse.classList.add('collapser');
}

function hideExtras(colresultElem) {
    const extras = colresultElem.parentNode.nextElementSibling;
    const expandcollapse = colresultElem.firstElementChild;
    extras.classList.add('collapsed');
    expandcollapse.classList.remove('collapser');
    expandcollapse.classList.add('expander');
}

function showFilters() {
    const filterItems = document.getElementsByClassName('filter');
    for (let i = 0; i < filterItems.length; i++)
        filterItems[i].hidden = false;
}

function addCollapse() {
    // Add links for show/hide all
    const resulttable = find('table#results-table');
    const showhideall = document.createElement('p');
    showhideall.innerHTML = '<a href="javascript:showAllExtras()">Show all details</a> / ' +
                            '<a href="javascript:hideAllExtras()">Hide all details</a>';
    resulttable.parentElement.insertBefore(showhideall, resulttable);

    // Add show/hide link to each result
    findAll('.col-result').forEach(function(elem) {
        const collapsed = getQueryParameter('collapsed') || 'Passed';
        const extras = elem.parentNode.nextElementSibling;
        const expandcollapse = document.createElement('span');
        if (extras.classList.contains('collapsed')) {
            expandcollapse.classList.add('expander');
        } else if (collapsed.includes(elem.innerHTML)) {
            extras.classList.add('collapsed');
            expandcollapse.classList.add('expander');
        } else {
            expandcollapse.classList.add('collapser');
        }
        elem.appendChild(expandcollapse);

        elem.addEventListener('click', function(event) {
            if (event.currentTarget.parentNode.nextElementSibling.classList.contains('collapsed')) {
                showExtras(event.currentTarget);
            } else {
                hideExtras(event.currentTarget);
            }
        });
    });
}

function getQueryParameter(name) {
    const match = RegExp('[?&]' + name + '=([^&]*)').exec(window.location.search);
    return match && decodeURIComponent(match[1].replace(/\+/g, ' '));
}

function init () { // eslint-disable-line no-unused-vars
    resetSortHeaders();

    addCollapse();

    showFilters();

    sortColumn(find('.initial-sort'));

    findAll('.sortable').forEach(function(elem) {
        elem.addEventListener('click',
            function() {
                sortColumn(elem);
            }, false);
    });
}

function sortTable(clicked, keyFunc) {
    const rows = findAll('.results-table-row');
    const reversed = !clicked.classList.contains('asc');
    const sortedRows = sort(rows, keyFunc, reversed);
    /* Whole table is removed here because browsers acts much slower
     * when appending existing elements.
     */
    const thead = document.getElementById('results-table-head');
    document.getElementById('results-table').remove();
    const parent = document.createElement('table');
    parent.id = 'results-table';
    parent.appendChild(thead);
    sortedRows.forEach(function(elem) {
        parent.appendChild(elem);
    });
    document.getElementsByTagName('BODY')[0].appendChild(parent);
}

function sort(items, keyFunc, reversed) {
    const sortArray = items.map(function(item, i) {
        return [keyFunc(item), i];
    });

    sortArray.sort(function(a, b) {
        const keyA = a[0];
        const keyB = b[0];

        if (keyA == keyB) return 0;

        if (reversed) {
            return keyA < keyB ? 1 : -1;
        } else {
            return keyA > keyB ? 1 : -1;
        }
    });

    return sortArray.map(function(item) {
        const index = item[1];
        return items[index];
    });
}

function keyAlpha(colIndex) {
    return function(elem) {
        return elem.childNodes[1].childNodes[colIndex].firstChild.data.toLowerCase();
    };
}

function keyLink(colIndex) {
    return function(elem) {
        const dataCell = elem.childNodes[1].childNodes[colIndex].firstChild;
        return dataCell == null ? '' : dataCell.innerText.toLowerCase();
    };
}

function keyResult(colIndex) {
    return function(elem) {
        const strings = ['Error', 'Failed', 'Rerun', 'XFailed', 'XPassed',
            'Skipped', 'Passed'];
        return strings.indexOf(elem.childNodes[1].childNodes[colIndex].firstChild.data);
    };
}

function resetSortHeaders() {
    findAll('.sort-icon').forEach(function(elem) {
        elem.parentNode.removeChild(elem);
    });
    findAll('.sortable').forEach(function(elem) {
        const icon = document.createElement('div');
        icon.className = 'sort-icon';
        icon.textContent = 'vvv';
        elem.insertBefore(icon, elem.firstChild);
        elem.classList.remove('desc', 'active');
        elem.classList.add('asc', 'inactive');
    });
}

function toggleSortStates(elem) {
    //if active, toggle between asc and desc
    if (elem.classList.contains('active')) {
        elem.classList.toggle('asc');
        elem.classList.toggle('desc');
    }

    //if inactive, reset all other functions and add ascending active
    if (elem.classList.contains('inactive')) {
        resetSortHeaders();
        elem.classList.remove('inactive');
        elem.classList.add('active');
    }
}

function isAllRowsHidden(value) {
    return value.hidden == false;
}

function filterTable(elem) { // eslint-disable-line no-unused-vars
    const outcomeAtt = 'data-test-result';
    const outcome = elem.getAttribute(outcomeAtt);
    const classOutcome = outcome + ' results-table-row';
    const outcomeRows = document.getElementsByClassName(classOutcome);

    for(let i = 0; i < outcomeRows.length; i++){
        outcomeRows[i].hidden = !elem.checked;
    }

    const rows = findAll('.results-table-row').filter(isAllRowsHidden);
    const allRowsHidden = rows.length == 0 ? true : false;
    const notFoundMessage = document.getElementById('not-found-message');
    notFoundMessage.hidden = !allRowsHidden;
}
</script>
    <h1>report.html</h1>
    <p>Report generated on 05-Sep-2021 at 19:31:32 by <a href="https://pypi.python.org/pypi/pytest-html">pytest-html</a> v3.1.1</p>
    <h2>Environment</h2>
    <table id="environment">
      <tr>
        <td>Module Name</td>
        <td>Customers</td></tr>
      <tr>
        <td>Platform</td>
        <td>Windows-10-10.0.19042-SP0</td></tr>
      <tr>
        <td>Plugins</td>
        <td>{"forked": "1.3.0", "html": "3.1.1", "metadata": "1.11.0", "xdist": "2.2.1"}</td></tr>
      <tr>
        <td>Project Name</td>
        <td>nop Commerce Admin App</td></tr>
      <tr>
        <td>Python</td>
        <td>3.9.6</td></tr>
      <tr>
        <td>Tester</td>
        <td>Siddharth</td></tr></table>
    <h2>Summary</h2>
    <p>12 tests ran in 184.14 seconds. </p>
    <p class="filter" hidden="true">(Un)check the boxes to filter the results.</p><input checked="true" class="filter" data-test-result="passed" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="passed">12 passed</span>, <input checked="true" class="filter" data-test-result="skipped" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="skipped">0 skipped</span>, <input checked="true" class="filter" data-test-result="failed" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="failed">0 failed</span>, <input checked="true" class="filter" data-test-result="error" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="error">0 errors</span>, <input checked="true" class="filter" data-test-result="xfailed" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="xfailed">0 expected failures</span>, <input checked="true" class="filter" data-test-result="xpassed" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="xpassed">0 unexpected passes</span>
    <h2>Results</h2>
    <table id="results-table">
      <thead id="results-table-head">
        <tr>
          <th class="sortable result initial-sort" col="result">Result</th>
          <th class="sortable" col="name">Test</th>
          <th class="sortable" col="duration">Duration</th>
          <th class="sortable links" col="links">Links</th></tr>
        <tr hidden="true" id="not-found-message">
          <th colspan="4">No results found. Try to check the filters</th></tr></thead>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">testCases/test_addcustomer.py::TestsAddNewCustomer::test_errormessage_noemail_registered_customer</td>
          <td class="col-duration">54.91</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">[gw1] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/>[gw1] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw1] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw1] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/> -----------------------------Captured stderr setup------------------------------ <br/>2021-09-05 19:28:29,928 - conftest.py:logger - CRITICAL - Find test run artifacts at: C:\Users\siddh\Google Drive\PycharmProjects\nopAdminSelenium\TestRuns\Test Run - 2021-09-05 19.28.29.871199\
2021-09-05 19:28:41,910 - test_addcustomer.py:setup - WARNING - Attempting login
<br/> -------------------------------Captured log setup------------------------------- <br/>CRITICAL custom_logger:conftest.py:171 Find test run artifacts at: C:\Users\siddh\Google Drive\PycharmProjects\nopAdminSelenium\TestRuns\Test Run - 2021-09-05 19.28.29.871199\
WARNING  custom_logger:test_addcustomer.py:21 Attempting login
INFO     custom_logger:test_addcustomer.py:24 login successful<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">testCases/test_addcustomer.py::TestsAddNewCustomer::test_alertmessage_noemail_registered_customer</td>
          <td class="col-duration">61.59</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">[gw2] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/>[gw2] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw2] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw2] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/> -----------------------------Captured stderr setup------------------------------ <br/>2021-09-05 19:28:30,059 - conftest.py:logger - CRITICAL - Find test run artifacts at: C:\Users\siddh\Google Drive\PycharmProjects\nopAdminSelenium\TestRuns\Test Run - 2021-09-05 19.28.29.871199\
2021-09-05 19:28:43,288 - test_addcustomer.py:setup - WARNING - Attempting login
<br/> -------------------------------Captured log setup------------------------------- <br/>CRITICAL custom_logger:conftest.py:171 Find test run artifacts at: C:\Users\siddh\Google Drive\PycharmProjects\nopAdminSelenium\TestRuns\Test Run - 2021-09-05 19.28.29.871199\
WARNING  custom_logger:test_addcustomer.py:21 Attempting login
INFO     custom_logger:test_addcustomer.py:24 login successful<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">testCases/test_addcustomer.py::TestsAddNewCustomer::test_add_customer</td>
          <td class="col-duration">69.41</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">[gw0] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/>[gw0] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw0] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw0] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/> -----------------------------Captured stderr setup------------------------------ <br/>2021-09-05 19:28:29,881 - conftest.py:logger - CRITICAL - Find test run artifacts at: C:\Users\siddh\Google Drive\PycharmProjects\nopAdminSelenium\TestRuns\Test Run - 2021-09-05 19.28.29.871199\
2021-09-05 19:28:44,119 - test_addcustomer.py:setup - WARNING - Attempting login
<br/> -------------------------------Captured log setup------------------------------- <br/>CRITICAL custom_logger:conftest.py:171 Find test run artifacts at: C:\Users\siddh\Google Drive\PycharmProjects\nopAdminSelenium\TestRuns\Test Run - 2021-09-05 19.28.29.871199\
WARNING  custom_logger:test_addcustomer.py:21 Attempting login
INFO     custom_logger:test_addcustomer.py:24 login successful<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">testCases/test_addcustomer.py::TestsAddNewCustomer::test_errormessage_role_cannot_be_both_registered_and_guests</td>
          <td class="col-duration">115.59</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">[gw3] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/>[gw3] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw3] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw3] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/> -----------------------------Captured stderr setup------------------------------ <br/>2021-09-05 19:28:29,997 - conftest.py:logger - CRITICAL - Find test run artifacts at: C:\Users\siddh\Google Drive\PycharmProjects\nopAdminSelenium\TestRuns\Test Run - 2021-09-05 19.28.29.871199\
2021-09-05 19:28:44,037 - test_addcustomer.py:setup - WARNING - Attempting login
<br/> -------------------------------Captured log setup------------------------------- <br/>CRITICAL custom_logger:conftest.py:171 Find test run artifacts at: C:\Users\siddh\Google Drive\PycharmProjects\nopAdminSelenium\TestRuns\Test Run - 2021-09-05 19.28.29.871199\
WARNING  custom_logger:test_addcustomer.py:21 Attempting login
INFO     custom_logger:test_addcustomer.py:24 login successful<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">testCases/test_addcustomer.py::TestDropDownLists::test_newsletter_dropdown</td>
          <td class="col-duration">52.22</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">[gw2] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/>[gw2] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw2] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw2] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/> -----------------------------Captured stderr setup------------------------------ <br/>2021-09-05 19:29:41,916 - test_addcustomer.py:setup - WARNING - Attempting login
<br/> -------------------------------Captured log setup------------------------------- <br/>WARNING  custom_logger:test_addcustomer.py:98 Attempting login
INFO     custom_logger:test_addcustomer.py:101 login successful<br/> ----------------------------Captured stdout teardown---------------------------- <br/>testCases/test_addcustomer.py::TestDropDownLists: An exception occurred while taking a screenshot
<br/> ----------------------------Captured stderr teardown---------------------------- <br/>2021-09-05 19:30:21,416 - conftest.py:driver_class_scoped - ERROR - testCases/test_addcustomer.py::TestDropDownLists: An exception occurred while taking a screenshot
Traceback (most recent call last):
  File &quot;C:\Users\siddh\Google Drive\PycharmProjects\nopAdminSelenium\testCases\conftest.py&quot;, line 154, in driver_class_scoped
    if all_test_functions[0].setup_result.failed:
AttributeError: &#x27;Function&#x27; object has no attribute &#x27;setup_result&#x27;
<br/> -----------------------------Captured log teardown------------------------------ <br/>ERROR    custom_logger:conftest.py:163 testCases/test_addcustomer.py::TestDropDownLists: An exception occurred while taking a screenshot
Traceback (most recent call last):
  File &quot;C:\Users\siddh\Google Drive\PycharmProjects\nopAdminSelenium\testCases\conftest.py&quot;, line 154, in driver_class_scoped
    if all_test_functions[0].setup_result.failed:
AttributeError: &#x27;Function&#x27; object has no attribute &#x27;setup_result&#x27;<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">testCases/test_addcustomer.py::TestDropDownLists::test_customer_roles_dropdown</td>
          <td class="col-duration">66.69</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">[gw1] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/>[gw1] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw1] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw1] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/> -----------------------------Captured stderr setup------------------------------ <br/>2021-09-05 19:29:37,063 - test_addcustomer.py:setup - WARNING - Attempting login
<br/> -------------------------------Captured log setup------------------------------- <br/>WARNING  custom_logger:test_addcustomer.py:98 Attempting login
INFO     custom_logger:test_addcustomer.py:101 login successful<br/> ----------------------------Captured stdout teardown---------------------------- <br/>testCases/test_addcustomer.py::TestDropDownLists: An exception occurred while taking a screenshot
<br/> ----------------------------Captured stderr teardown---------------------------- <br/>2021-09-05 19:30:29,183 - conftest.py:driver_class_scoped - ERROR - testCases/test_addcustomer.py::TestDropDownLists: An exception occurred while taking a screenshot
Traceback (most recent call last):
  File &quot;C:\Users\siddh\Google Drive\PycharmProjects\nopAdminSelenium\testCases\conftest.py&quot;, line 158, in driver_class_scoped
    elif False in [test.call_result.passed for test in
  File &quot;C:\Users\siddh\Google Drive\PycharmProjects\nopAdminSelenium\testCases\conftest.py&quot;, line 158, in &lt;listcomp&gt;
    elif False in [test.call_result.passed for test in
AttributeError: &#x27;Function&#x27; object has no attribute &#x27;call_result&#x27;
<br/> -----------------------------Captured log teardown------------------------------ <br/>ERROR    custom_logger:conftest.py:163 testCases/test_addcustomer.py::TestDropDownLists: An exception occurred while taking a screenshot
Traceback (most recent call last):
  File &quot;C:\Users\siddh\Google Drive\PycharmProjects\nopAdminSelenium\testCases\conftest.py&quot;, line 158, in driver_class_scoped
    elif False in [test.call_result.passed for test in
  File &quot;C:\Users\siddh\Google Drive\PycharmProjects\nopAdminSelenium\testCases\conftest.py&quot;, line 158, in &lt;listcomp&gt;
    elif False in [test.call_result.passed for test in
AttributeError: &#x27;Function&#x27; object has no attribute &#x27;call_result&#x27;<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">testCases/test_addcustomer.py::TestsAddNewCustomer::test_alertmessage_role_cannot_be_both_registered_and_guests</td>
          <td class="col-duration">63.28</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">[gw0] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/>[gw0] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw0] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw0] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/> -----------------------------Captured stderr setup------------------------------ <br/>2021-09-05 19:29:47,023 - test_addcustomer.py:setup - WARNING - Attempting login
<br/> -------------------------------Captured log setup------------------------------- <br/>WARNING  custom_logger:test_addcustomer.py:21 Attempting login
INFO     custom_logger:test_addcustomer.py:24 login successful<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">testCases/test_login.py::TestsLogIn::test_incorrect_password[testdata0]</td>
          <td class="col-duration">14.12</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">[gw2] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/>[gw2] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw2] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw2] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/> -------------------------------Captured log call-------------------------------- <br/>INFO     custom_logger:test_login.py:29 Attempting login with useremail:ram@gmail.com and password:#$%rjry
INFO     custom_logger:test_login.py:41 login failed as expected. Test DataRow no: 2<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">testCases/test_login.py::TestsLogIn::test_login</td>
          <td class="col-duration">24.45</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">[gw1] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/>[gw1] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw1] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw1] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/> ------------------------------Captured stderr call------------------------------ <br/>2021-09-05 19:30:38,467 - test_login.py:test_login - WARNING - Attempting login
<br/> -------------------------------Captured log call-------------------------------- <br/>WARNING  custom_logger:test_login.py:21 Attempting login
INFO     custom_logger:test_login.py:24 login successful<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">testCases/test_login.py::TestsLogIn::test_incorrect_password[testdata2]</td>
          <td class="col-duration">12.26</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">[gw2] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/>[gw2] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw2] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw2] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/> -------------------------------Captured log call-------------------------------- <br/>INFO     custom_logger:test_login.py:29 Attempting login with useremail:cold@hotmail.com and password:gh$%,k
INFO     custom_logger:test_login.py:41 login failed as expected. Test DataRow no: 4<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">testCases/test_login.py::TestsLogIn::test_incorrect_password[testdata1]</td>
          <td class="col-duration">14.96</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">[gw0] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/>[gw0] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw0] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw0] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/> -------------------------------Captured log call-------------------------------- <br/>INFO     custom_logger:test_login.py:29 Attempting login with useremail:mohan@yahoo.com and password:^3456kfg
INFO     custom_logger:test_login.py:41 login failed as expected. Test DataRow no: 3<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">testCases/test_addcustomer.py::TestDropDownLists::test_vendor_manager_dropdown</td>
          <td class="col-duration">66.49</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">[gw3] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/>[gw3] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw3] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe[gw3] win32 -- Python 3.9.6 c:\users\siddh\google drive\pycharmprojects\nopadminselenium\venv\scripts\python.exe<br/> -----------------------------Captured stderr setup------------------------------ <br/>2021-09-05 19:30:40,063 - test_addcustomer.py:setup - WARNING - Attempting login
<br/> -------------------------------Captured log setup------------------------------- <br/>WARNING  custom_logger:test_addcustomer.py:98 Attempting login
INFO     custom_logger:test_addcustomer.py:101 login successful<br/> ----------------------------Captured stdout teardown---------------------------- <br/>testCases/test_addcustomer.py::TestDropDownLists: An exception occurred while taking a screenshot
<br/> ----------------------------Captured stderr teardown---------------------------- <br/>2021-09-05 19:31:29,810 - conftest.py:driver_class_scoped - ERROR - testCases/test_addcustomer.py::TestDropDownLists: An exception occurred while taking a screenshot
Traceback (most recent call last):
  File &quot;C:\Users\siddh\Google Drive\PycharmProjects\nopAdminSelenium\testCases\conftest.py&quot;, line 154, in driver_class_scoped
    if all_test_functions[0].setup_result.failed:
AttributeError: &#x27;Function&#x27; object has no attribute &#x27;setup_result&#x27;
<br/> -----------------------------Captured log teardown------------------------------ <br/>ERROR    custom_logger:conftest.py:163 testCases/test_addcustomer.py::TestDropDownLists: An exception occurred while taking a screenshot
Traceback (most recent call last):
  File &quot;C:\Users\siddh\Google Drive\PycharmProjects\nopAdminSelenium\testCases\conftest.py&quot;, line 154, in driver_class_scoped
    if all_test_functions[0].setup_result.failed:
AttributeError: &#x27;Function&#x27; object has no attribute &#x27;setup_result&#x27;<br/></div></td></tr></tbody></table></body></html>