2021-03-29 16:07:21,199 - test_login.py:test_incorrect_password - INFO - Attempting login with useremail:admin@yourstore.com and password:admin
2021-03-29 16:09:55,733 - test_login.py:test_incorrect_password - ERROR - Test Case failed for useremail:admin@yourstore.com and password:admin. Test DataRow no: 5
Traceback (most recent call last):
  File "C:\Users\Siddharth\Google Drive\PycharmProjects\nopAdminSelenium\testCases\test_login.py", line 32, in test_incorrect_password
    assert "login" in lp.get_title().lower()
AssertionError: assert 'login' in 'dashboard / nopcommerce administration'
 +  where 'dashboard / nopcommerce administration' = <built-in method lower of str object at 0x05322920>()
 +    where <built-in method lower of str object at 0x05322920> = 'Dashboard / nopCommerce administration'.lower
 +      where 'Dashboard / nopCommerce administration' = <bound method BasePage.get_title of <pageObjects.loginpage.LoginPage object at 0x0532F520>>()
 +        where <bound method BasePage.get_title of <pageObjects.loginpage.LoginPage object at 0x0532F520>> = <pageObjects.loginpage.LoginPage object at 0x0532F520>.get_title
2021-03-29 16:11:07,876 - conftest.py:pytest_runtest_makereport - ERROR - Test case --> testCases/test_login.py::TestsLogIn::test_incorrect_password[testdata3] failed. Error Message:
 <ExceptionInfo <Failed instance> tblen=1>
2021-03-29 16:11:07,876 - conftest.py:pytest_runtest_makereport - ERROR - Test case --> testCases/test_login.py::TestsLogIn::test_incorrect_password[testdata3] failed. Error Message:
 <ExceptionInfo <Failed instance> tblen=1>
